-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgl0wOWCdH0rHb8+vu
MqM7PC92OuHDz/H7QzDK7+dgZKygCgYIKoZIzj0DAQehRANCAASkhqgJ4qIDNnkt
ZR+oPVsFJzxxHGWa2if4w8AxKVW+MQZLFT1AF0Sn6fLP6c+SNqU/MGyJJsN7LKhr
X5caVFdi
-----END PRIVATE KEY-----